// import game from "assets/game-changing-1000x600.jpg"
// import mobile2 from "assets/mobile2.jpg"
// import mobile3 from "assets/mobile3.jpg"
// import mobile4 from "assets/mobile4.jpg"
// import digital1 from "assets/how-to-make1000x600.jpg"
// import digital2 from "assets/digital2-1300x650.jpg"
// import digital3 from "assets/digital31000x600.jpg"
// import gadget1 from "assets/gadget1-1000x600.jpg"
// import gadget3 from "assets/gadget3-450x350.jpg"
// import stylishBohemianCouple from "assets/stylish-bohemian-couple-700x700.jpg"

type Article = {
    categoriy   :string
    subcategoriy:string
    srcImg    : string
    altImg    :string
    hrefTitle :string
    titleShot :string
    titleAll  :string
    titleViews:string
    excerpt :string
    views: number
    autor:string
    dates:string
    lastRead :string
    comentsNum :number
    likes: number
}

const articleArray: Article[] =[
    {
        categoriy   :'Travel',
        subcategoriy:'Travel',
        srcImg    : `{stylishBohemianCouple}` ,
        altImg    :'Stylish Bohemian Couple',
        hrefTitle :'https:/',
        titleShot :'10 Honeymoon Destinations for Every Budget',
        titleAll  :'10 Honeymoon Destinations for Every Budget',
        titleViews:'112 Views',
        excerpt :'',
        views: 1,
        autor:'John Nikova',
        dates:'August 26, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        categoriy   :'Entertainment',
        subcategoriy:'Travel',
        srcImg    :'{woodenBridgeKoh}',
        altImg    :'Wooden Bridge Koh',
        hrefTitle :'https:/',
        titleShot :'15 Underrated but Amazing Island Vacations',
        titleAll  :'15 Underrated but Amazing Island Vacations',
        titleViews:'81 Views',
        excerpt :'',
        views: 1,
        autor:'John Nikova',
        dates:'August 26, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        categoriy   :'Lifestyle',
        subcategoriy:'Travel',
        srcImg    :'{womanWithHat}',
        altImg    :'Woman With Hat',
        hrefTitle :'https:/',
        titleShot :'How a Beach Vacation Can be a Skincare Treatment',
        titleAll  :'How a Beach Vacation Can be a Skincare Treatment',
        titleViews:'98 Views',
        excerpt :'',
        views: 1,
        autor:'John Nikova',
        dates:'August 26, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        categoriy   :'Travel',
        subcategoriy:'Travel',
        srcImg    :'{bikiniGirlHolding}',
        altImg    :'Bikini Girl Holding',
        hrefTitle :'https:/',
        titleShot :'How to Turn a Mini Camera into a PowerTech',
        titleAll  :'HHow to Turn a Mini Camera into a PowerTech',
        titleViews:'88 View',
        excerpt :'',
        views: 1,
        autor:'John Nikova',
        dates:'August 26, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        categoriy   :'Mobile',
        subcategoriy:'Digital',
        srcImg    :'{mobile}',
        altImg    :'Sony Laptops Are',
        hrefTitle :'https:/',
        titleShot :'Sony Laptops Are Still Part Of The Sony Family',
        titleAll  :'Sony Laptops Are Still Part Of The Sony Family',
        titleViews:'6 Posts',
        excerpt :'Far far away, behind the word mountains, far from the countries Vokalia and...',
        views: 1,
        autor:'John Nikova',
        dates:'September 26, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        categoriy   :'Mobile',
        subcategoriy:'Digital',
        srcImg    :'{mobile2}',
        altImg    :'Digital Calendars',
        hrefTitle :'https:/',
        titleShot :'Digital Calendars & Organizers to Get You Organized',
        titleAll  :'Digital Calendars & Organizers to Get You Organized',
        titleViews:'6 Posts',
        excerpt :'Far far away, behind the word mountains, far from the countries Vokalia and...',
        views: 1,
        autor:'John Nikova',
        dates:'September 11, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        categoriy   :'Mobile',
        subcategoriy:'Gadget',
        srcImg    :'{mobile3}',
        altImg    :'DEverything You Wanted',
        hrefTitle :'https:/',
        titleShot :'Everything You Wanted to Know About Technology',
        titleAll  :'Everything You Wanted to Know About Technology',
        titleViews:'6 Posts',
        excerpt :'Far far away, behind the word mountains, far from the countries Vokalia and...',
        views: 1,
        autor:'John Nikova',
        dates:'August 9, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        categoriy   :'Travel',
        subcategoriy:'Travel',
        srcImg    :'{lost}',
        altImg    :'Travel in Bermuda',
        hrefTitle :'https:/',
        titleShot :'Travel in Bermuda: Read Tips & Tricks to the Island Life',
        titleAll  :'Travel in Bermuda: Read Tips & Tricks to the Island Life',
        titleViews:'6 Posts',
        excerpt :'Far far away, behind the word mountains, far from the countries Vokalia and...',
        views: 1,
        autor:'John Nikova',
        dates:'October 1, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        categoriy   :'Mobile',
        subcategoriy:'Gadget',
        srcImg    :'{mobile4}',
        altImg    :'Digital Calendars',
        hrefTitle :'https:/',
        titleShot :'AI Needs Your Data and You Should Get Paid for It',
        titleAll  :'AI Needs Your Data and You Should Get Paid for It',
        titleViews:'6 Posts',
        excerpt :'Far far away, behind the word mountains, far from the countries Vokalia and...',
        views: 1,
        autor:'John Nikova',
        dates:'April 13, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        categoriy   :'Travel',
        subcategoriy:'Lifestyle',
        srcImg    :'{sexyStylish}',
        altImg    :'Most Beautiful Days',
        hrefTitle :'https:/',
        titleShot :'Most Beautiful Days in Sydney Have Started',
        titleAll  :'Most Beautiful Days in Sydney Have Started',
        titleViews:'6 Posts',
        excerpt :'Far far away, behind the word mountains, far from the countries Vokalia and...',
        views: 1,
        autor:'John Nikova',
        dates:'August 10, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        categoriy   :'Digital',
        subcategoriy:'Digital',
        srcImg    :'{game}',
        altImg    :'Game Changing Virtual',
        hrefTitle :'https:/',
        titleShot :'Game Changing Virtual Reality Console',
        titleAll  :'Game Changing Virtual Reality Console',
        titleViews:'6 Posts',
        excerpt :'Far far away, behind the word mountains, far from the countries Vokalia and...',
        views: 1,
        autor:'John Nikova',
        dates:'October 8, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        categoriy   :'Digital',
        subcategoriy:'Digital',
        srcImg    :'{digital1}',
        altImg    :'How to Make',
        hrefTitle :'https:/',
        titleShot :'How to Make a Competitor`s Success Work for You',
        titleAll  :'How to Make a Competitor`s Success Work for You',
        titleViews:'6 Posts',
        excerpt :'Far far away, behind the word mountains, far from the countries Vokalia and...',
        views: 1,
        autor:'John Nikova',
        dates:'October 7, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        categoriy   :'Digital',
        subcategoriy:'Gadget',
        srcImg    :'{digital3}',
        altImg    :'Innovative VR Screen',
        hrefTitle :'https:/',
        titleShot :'Innovative VR Screen and Control Tech Debuts at CES',
        titleAll  :'Innovative VR Screen and Control Tech Debuts at CES',
        titleViews:'6 Posts',
        excerpt :'Far far away, behind the word mountains, far from the countries Vokalia and...',
        views: 1,
        autor:'John Nikova',
        dates:' July 19, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        categoriy   :'Digital',
        subcategoriy:'Digital',
        srcImg    :'{digital2}',
        altImg    :'Extend Work Until',
        hrefTitle :'https:/',
        titleShot :'Google, Facebook Extend Work Until 2021',
        titleAll  :'Google, Facebook Extend Work Until 2021',
        titleViews:'6 Posts',
        excerpt :'Far far away, behind the word mountains, far from the countries Vokalia and...',
        views: 1,
        autor:'John Nikova',
        dates:'September 15, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        categoriy   :'Gadget',
        subcategoriy:'Gadget',
        srcImg    :'{prettyBlondeGirl}',
        altImg    :'Extend Work Until',
        hrefTitle :'https:/',
        titleShot :'Top 5 New Tech Gadgets You Must Have In 2023',
        titleAll  :'Top 5 New Tech Gadgets You Must Have In 2023',
        titleViews:'6 Posts',
        excerpt :'Far far away, behind the word mountains, far from the countries Vokalia and...',
        views: 1,
        autor:'John Nikova',
        dates:'September 3, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        categoriy   :'Gadget',
        subcategoriy:'Digital',
        srcImg    :'{gadget1}',
        altImg    :'Ultimate Gadgets',
        hrefTitle :'https:/',
        titleShot :'Ultimate Gadgets Guide + What Is Hot This Season',
        titleAll  :'Ultimate Gadgets Guide + What Is Hot This Season',
        titleViews:'6 Posts',
        excerpt :'Far far away, behind the word mountains, far from the countries Vokalia and...',
        views: 1,
        autor:'John Nikova',
        dates:'August 21, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        categoriy   :'Gadget',
        subcategoriy:'Entertainment',
        srcImg    :'{gadget3}',
        altImg    :'A Smarter Way',
        hrefTitle :'https:/',
        titleShot :'A Smarter Way to Think About Intelligent Machines',
        titleAll  :'A Smarter Way to Think About Intelligent Machines',
        titleViews:'6 Posts',
        excerpt :'Far far away, behind the word mountains, far from the countries Vokalia and...',
        views: 1,
        autor:'John Nikova',
        dates:'August 7, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
]
export default articleArray