// import game from "images/game-changing-1000x600.jpg"
// import mobile2 from "images/mobile2.jpg"
// import mobile3 from "images/mobile3.jpg"
// import mobile4 from "images/mobile4.jpg"
// import digital1 from "images/how-to-make1000x600.jpg"
// import digital2 from "images/digital2-1300x650.jpg"
// import digital3 from "images/digital31000x600.jpg"
// import gadget1 from "images/gadget1-1000x600.jpg"
// import gadget3 from "images/gadget3-450x350.jpg"
// import stylishBohemianCouple from "images/stylish-bohemian-couple-700x700.jpg"

type Article = {
    id:number
    categoriy   :string
    subcategoriy:string
    srcImg    : string
    altImg    :string
    hrefTitle :string
    titleShot :string
    titleAll  :string
    titleViews:string
    excerpt :string
    views: number
    autor:string
    dates:string
    lastRead :string
    comentsNum :number
    likes: number
}

const articleArray: Article[] =[
    {
        id:1,
        categoriy   :'Travel',
        subcategoriy:'Travel',
        srcImg    : "images/stylish-bohemian-couple-700x700.jpg" ,
        altImg    :'Stylish Bohemian Couple',
        hrefTitle :'https:/',
        titleShot :'10 Honeymoon Destinations for Every Budget',
        titleAll  :'10 Honeymoon Destinations for Every Budget',
        titleViews:'112 Views',
        excerpt :'',
        views: 1,
        autor:'John Nikova',
        dates:'August 26, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        id:2,
        categoriy   :'Entertainment',
        subcategoriy:'Travel',
        srcImg    :'images/wooden-bridge-koh-700x700.jpg',
        altImg    :'Wooden Bridge Koh',
        hrefTitle :'https:/',
        titleShot :'15 Underrated but Amazing Island Vacations',
        titleAll  :'15 Underrated but Amazing Island Vacations',
        titleViews:'81 Views',
        excerpt :'',
        views: 1,
        autor:'John Nikova',
        dates:'August 26, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        id:3,
        categoriy   :'Lifestyle',
        subcategoriy:'Travel',
        srcImg    :'images/woman-with-hat-700x700.jpg',
        altImg    :'Woman With Hat',
        hrefTitle :'https:/',
        titleShot :'How a Beach Vacation Can be a Skincare Treatment',
        titleAll  :'How a Beach Vacation Can be a Skincare Treatment',
        titleViews:'98 Views',
        excerpt :'',
        views: 1,
        autor:'John Nikova',
        dates:'August 26, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        id:4,
        categoriy   :'Travel',
        subcategoriy:'Travel',
        srcImg    :'images/bikini-girl-holding-700x700.jpg',
        altImg    :'Bikini Girl Holding',
        hrefTitle :'https:/',
        titleShot :'How to Turn a Mini Camera into a PowerTech',
        titleAll  :'HHow to Turn a Mini Camera into a PowerTech',
        titleViews:'88 View',
        excerpt :'',
        views: 1,
        autor:'John Nikova',
        dates:'August 26, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        id:5,
        categoriy   :'Mobile',
        subcategoriy:'Digital',
        srcImg    :'images/mobile-1000x600.jpg',
        altImg    :'Sony Laptops Are',
        hrefTitle :'https:/',
        titleShot :'Sony Laptops Are Still Part Of The Sony Family',
        titleAll  :'Sony Laptops Are Still Part Of The Sony Family',
        titleViews:'6 Posts',
        excerpt :'Far far away, behind the word mountains, far from the countries Vokalia and...',
        views: 1,
        autor:'John Nikova',
        dates:'September 26, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        id:6,
        categoriy   :'Mobile',
        subcategoriy:'Digital',
        srcImg    :'images/mobile2.jpg',
        altImg    :'Digital Calendars',
        hrefTitle :'https:/',
        titleShot :'Digital Calendars & Organizers to Get You Organized',
        titleAll  :'Digital Calendars & Organizers to Get You Organized',
        titleViews:'6 Posts',
        excerpt :'Far far away, behind the word mountains, far from the countries Vokalia and...',
        views: 1,
        autor:'John Nikova',
        dates:'September 11, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        id:7,
        categoriy   :'Mobile',
        subcategoriy:'Gadget',
        srcImg    :'images/mobile3.jpg',
        altImg    :'DEverything You Wanted',
        hrefTitle :'https:/',
        titleShot :'Everything You Wanted to Know About Technology',
        titleAll  :'Everything You Wanted to Know About Technology',
        titleViews:'6 Posts',
        excerpt :'Far far away, behind the word mountains, far from the countries Vokalia and...',
        views: 1,
        autor:'John Nikova',
        dates:'August 9, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        id:8,
        categoriy   :'Travel',
        subcategoriy:'Travel',
        srcImg    :'images/lost-tourists-450x350.jpg',
        altImg    :'Travel in Bermuda',
        hrefTitle :'https:/',
        titleShot :'Travel in Bermuda: Read Tips & Tricks to the Island Life',
        titleAll  :'Travel in Bermuda: Read Tips & Tricks to the Island Life',
        titleViews:'6 Posts',
        excerpt :'Far far away, behind the word mountains, far from the countries Vokalia and...',
        views: 1,
        autor:'John Nikova',
        dates:'October 1, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        id:9,
        categoriy   :'Mobile',
        subcategoriy:'Gadget',
        srcImg    :'images/mobile4.jpg',
        altImg    :'Digital Calendars',
        hrefTitle :'https:/',
        titleShot :'AI Needs Your Data and You Should Get Paid for It',
        titleAll  :'AI Needs Your Data and You Should Get Paid for It',
        titleViews:'6 Posts',
        excerpt :'Far far away, behind the word mountains, far from the countries Vokalia and...',
        views: 1,
        autor:'John Nikova',
        dates:'April 13, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        id:10,
        categoriy   :'Travel',
        subcategoriy:'Lifestyle',
        srcImg    :'images/sexy-stylish-450x350.jpg',
        altImg    :'Most Beautiful Days',
        hrefTitle :'https:/',
        titleShot :'Most Beautiful Days in Sydney Have Started',
        titleAll  :'Most Beautiful Days in Sydney Have Started',
        titleViews:'6 Posts',
        excerpt :'Far far away, behind the word mountains, far from the countries Vokalia and...',
        views: 1,
        autor:'John Nikova',
        dates:'August 10, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        id:11,
        categoriy   :'Digital',
        subcategoriy:'Digital',
        srcImg    :'images/game-changing-1000x600.jpg',
        altImg    :'Game Changing Virtual',
        hrefTitle :'https:/',
        titleShot :'Game Changing Virtual Reality Console',
        titleAll  :'Game Changing Virtual Reality Console',
        titleViews:'6 Posts',
        excerpt :'Far far away, behind the word mountains, far from the countries Vokalia and...',
        views: 1,
        autor:'John Nikova',
        dates:'October 8, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        id:12,
        categoriy   :'Digital',
        subcategoriy:'Digital',
        srcImg    :'images/how-to-make1000x600.jpg',
        altImg    :'How to Make',
        hrefTitle :'https:/',
        titleShot :'How to Make a Competitor`s Success Work for You',
        titleAll  :'How to Make a Competitor`s Success Work for You',
        titleViews:'6 Posts',
        excerpt :'Far far away, behind the word mountains, far from the countries Vokalia and...',
        views: 1,
        autor:'John Nikova',
        dates:'October 7, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        id:13,
        categoriy   :'Digital',
        subcategoriy:'Gadget',
        srcImg    :'images/digital31000x600.jpg',
        altImg    :'Innovative VR Screen',
        hrefTitle :'https:/',
        titleShot :'Innovative VR Screen and Control Tech Debuts at CES',
        titleAll  :'Innovative VR Screen and Control Tech Debuts at CES',
        titleViews:'6 Posts',
        excerpt :'Far far away, behind the word mountains, far from the countries Vokalia and...',
        views: 1,
        autor:'John Nikova',
        dates:' July 19, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        id:14,
        categoriy   :'Digital',
        subcategoriy:'Digital',
        srcImg    :'images/digital2-1300x650.jpg',
        altImg    :'Extend Work Until',
        hrefTitle :'https:/',
        titleShot :'Google, Facebook Extend Work Until 2021',
        titleAll  :'Google, Facebook Extend Work Until 2021',
        titleViews:'6 Posts',
        excerpt :'Far far away, behind the word mountains, far from the countries Vokalia and...',
        views: 1,
        autor:'John Nikova',
        dates:'September 15, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        id:15,
        categoriy   :'Gadget',
        subcategoriy:'Gadget',
        srcImg    :'images/pretty-blonde-girl-1300x650.jpg',
        altImg    :'Extend Work Until',
        hrefTitle :'https:/',
        titleShot :'Top 5 New Tech Gadgets You Must Have In 2023',
        titleAll  :'Top 5 New Tech Gadgets You Must Have In 2023',
        titleViews:'6 Posts',
        excerpt :'Far far away, behind the word mountains, far from the countries Vokalia and...',
        views: 1,
        autor:'John Nikova',
        dates:'September 3, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        id:16,
        categoriy   :'Gadget',
        subcategoriy:'Digital',
        srcImg    :'images/gadget1-1000x600.jpg',
        altImg    :'Ultimate Gadgets',
        hrefTitle :'https:/',
        titleShot :'Ultimate Gadgets Guide + What Is Hot This Season',
        titleAll  :'Ultimate Gadgets Guide + What Is Hot This Season',
        titleViews:'6 Posts',
        excerpt :'Far far away, behind the word mountains, far from the countries Vokalia and...',
        views: 1,
        autor:'John Nikova',
        dates:'August 21, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
    {
        id:17,
        categoriy   :'Gadget',
        subcategoriy:'Entertainment',
        srcImg    :'images/gadget3-450x350.jpg',
        altImg    :'A Smarter Way',
        hrefTitle :'https:/',
        titleShot :'A Smarter Way to Think About Intelligent Machines',
        titleAll  :'A Smarter Way to Think About Intelligent Machines',
        titleViews:'6 Posts',
        excerpt :'Far far away, behind the word mountains, far from the countries Vokalia and...',
        views: 1,
        autor:'John Nikova',
        dates:'August 7, 2022',
        lastRead :' 4 Mins Read',
        comentsNum :1,
        likes: 0,  
    },
]
export default articleArray